version: "3.8"

services:
  server:
    container_name: name-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    # ports:
    #   - 5000:5000
    command: "yarn dev"
  client:
    container_name: name-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    # ports:
    #   - 3000:3000
    command: "yarn dev"
  database:
    container_name: name-database
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - /database/:/var/lib/postgresql/data/
  nginx:
    image: nginx
    container_name: name-nginx
    # build:
    #   context: "./nginx"
    #   dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
