version: "3.8"

services:
  # server:
  #   container_name: name-backend
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 5000:5000
  #   command: "yarn dev"
  # client:
  #   container_name: name-frontend
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  database:
    container_name: name-database
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - /database/:/var/lib/postgresql/data/
